source 'https://github.com/CocoaPods/Specs.git'

target :URLShortenerWidget do
  pod 'Mixpanel/AppExtension'
  pod 'Shimmer'
end

target :URLShortenerAction do
  pod 'Mixpanel/AppExtension'
end

target :URLShortener do
  pod 'SVProgressHUD'
  pod 'Mixpanel'
end
